vercel.json

Just removes the comment on every merge about Vercel.

chore(deploy): silence vercel

---

.github/workflows/test.yaml

update GH actions (checkout/setup-node) to v3

---

pages/resources/channel.mdx

bros are for real 🥸 @Dziurwa14 @Dolfies

correct channel flag name from last PR

---

pages/resources/user.mdx

This is pretty self-explantory and just fixes a small formatting error. :)

Fix formatting error in user.md.

---

pages/topics/gateway-events.mdx
pages/topics/opcodes-and-status-codes.mdx

Based on the following RE-d code
```ts
interface State {
pageSize: number;
currentPage: number;
continuationToken: string | null;
}
interface PartialGuildMembersChunk {
members: { joined_at: string; user: { id: string } }[];
}
const searchChunkSize = 1e3;
function getMemberCount(guildId: string): number | undefined {
return; /* get count */
}
function getSortedMemberIDs(
members: { joinedAtTimestamp: Date; id: string }[]
) {
return members
.sort(member => -member.joinedAtTimestamp)
.map(member => member.id);
}
function calculateNewContinuationToken(
guildId: string,
sortedMemberIDs: string[],
state: State
) {
const memberCount = getMemberCount(guildId) ?? sortedMemberIDs.length;
const sortedMemberSize = sortedMemberIDs.length - 1;
const lastMemberID = sortedMemberIDs[sortedMemberSize]; …
```

Add OP 35 documentation

---

components/Navigation.tsx
pages/reference.mdx
pages/topics/client-distribution.mdx

- Downloads
- Updates
- v1 stack
- v2 stack
- Mobile shenanigans

Document distribution API

---

pages/resources/user.mdx

it's not exactly the same as the API, details can be found [here](https://github.com/discord-userdoccers/discord-userdoccers/pull/148)

feat: Update Required Action Type

---

pages/topics/gateway-events.mdx

Only checks the first 100 ids:

Document OP 34 (Request Last Messages)

---

pages/resources/message.mdx

also 2 attachment options related to voice messages

Add attachment flags & voice message fields

---

pages/resources/user.mdx

Add Roblox and Bungie.net connection types

---

pages/resources/channel.mdx

fix "stop ringing channel recipients" method

---

pages/resources/quests.mdx

fix(Quests): More quest fixes

---

pages/resources/sticker.mdx

just saw that when was viewing docs.

fix "emnployee" typo

---

pages/resources/guild.mdx

Not entirely fully tested, fully testing is hard

Document member elasticsearch

---

pages/resources/message.mdx

No description cuz it does nothing besides applying some css padding and hiding attachments.
Closes #221

Add `IS_UIKIT_COMPONENTS` (1 << 15) message flag

---

pages/resources/user.mdx
pages/topics/gateway-events.mdx

Don't know if `is_spam_request` is optional or nullable because client defaults to `false`
```js
V(["RELATIONSHIP_ADD"], e => {
j({
type: "RELATIONSHIP_ADD",
relationship: {
id: e.id,
type: e.type,
user: e.user,
since: e.since,
nickname: e.nickname,
isSpamRequest: e.is_spam_request || !1
},
shouldNotify: !0 === e.should_notify
})
}
),
V(["RELATIONSHIP_REMOVE"], e => {
j({
type: "RELATIONSHIP_REMOVE",
relationship: e
})
}
),
V(["RELATIONSHIP_UPDATE"], e => {
j({
type: "RELATIONSHIP_UPDATE",
relationship: {
id: e.id,
type: e.type,
user: e.user,
nickname: e.nickname,
since: e.since,
isSpamRequest: e.is_spam_request || !1
}
})
}
),
```

Update relationship docs

---

components/Navigation.tsx
pages/topics/oauth2.mdx

feat(oauth2): document PKCE

---

next.config.mjs

Adds redirect to this repo at https://docs.discord.sex/_github purely for convenience

feat(meta): add redirect at /_github

---

ci/sitemap.ts
components/navigation/NavigationList.tsx
pages/resources/channel.mdx

Add detailed response when a user is typing in the channel

---

package.json

otherwise this causes it to 500 because it can't find data.json

Build sitemap on `pnpm dev`

---

components/mdx/Table.tsx
lib/type-generator/languageConfig.ts
lib/type-generator/python.ts
lib/type-generator/store.tsx
lib/type-generator/tokenizer.ts
lib/type-generator/typescript.ts
tsconfig.json

refactor table copy

---

.github/workflows/deploy.yaml
ci/deploy.ts
package.json
pnpm-lock.yaml
wrangler.jsonc
wrangler.toml

this supports preview deployments for pull requests and for branches that aren't marked as production branch
waiting on @dolfies to unlink the github repo so i can enable the push event

feat(workflows/deploy.yaml): add custom deployment workflow

---

.github/workflows/deploy.yaml

feat(workflows/deploy): add pr metdata

---

pages/resources/message.mdx

also fixed "delete dm message" ep

Document pins v2

---

pages/resources/presence.mdx
pages/resources/relationships.mdx

the description is definitely terrible

Document Relationship.has_played_game

---

pages/resources/message.mdx
pages/resources/safety-hub.mdx

This is quite displeasing to me.

Document Safety Hub
